apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}
  namespace: moonpay
  labels:
    app: moonpay
    pr: "${PR_NUMBER}"
spec:
  type: ClusterIP
  selector:
    app: moonpay
    pr: "${PR_NUMBER}"
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
